# This config file uses `repo: local` to ensure that all tools
# use the same versions both locally and in the pre-commit hooks.
# Since local repos cannot use the `.pre-commit-hooks.yaml` file,
# we have to manually define the hooks here, based on the hooks
# as defined in the tools' upstream repo.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
     - id: mypy
       types_or: [ python, pyi ]
       args: ["--ignore-missing-imports", "--scripts-are-modules"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
